### ISSUE TITLE
Revanced 17.41.37 will not register as app in microg

### ISSUE THREAD

**Issue by TheUntouchable** [inotia00/VancedMicroG#1]
I switched from the [old vanced microg](https://github.com/TeamVanced/VancedMicroG/releases) to this (latest) version as it is much newer and maintained, but now the revanced youtube app is no longer registered in the microg and therefore I don't get notifications even though the account I registered in the microg is used in the youtube app correctly.
MicroG Support and Client Spoof is patched into the youtube app.
![Screenshot_20221029-204724](https://user-images.githubusercontent.com/2162540/198847959-f745127d-b556-40a7-bded-f678765ad00f.png)

**Comment by inotia00** [comment]
This issue occurs when you reinstall MicroG without reinstalling Vanced or ReVanced.

solution
1. Uninstall all MicroG, Vanced, and ReVanced.
2. Then, install MicroG first.
3. Turn off MicroG's battery optimization.
4. Install Vanced or ReVanced.
5. Confirm that Vanced or ReVanced has been successfully added to Cloud Messaging on MicroG.

If this solution solves the issue, please close it.

**Comment by TheUntouchable** [comment]
Hi @inotia00  and thanks for the quick reply :)
I just uninstalled everything related to vanced and tried the steps you mentioned, unfortunately that didn't solve the problem :( Anything I can provide you with?

**Comment by inotia00** [comment]
It's a temporary way, but try the following methods

Install the previous version of [MicroG](https://github.com/inotia00/VancedMicroG/releases/tag/v0.2.25.223212-223212002) release and try the above solution.

If you are normally added to the Cloud Messaging list, try update with the latest build.

Many have solved the issue through this method.

Nevertheless, if the issue is not solved, I think this should be seen as an Android 13 issue. (Restricted foreground notification due to Android 13 policy)

**Comment by TheUntouchable** [comment]
That workaround fixed the problem, thanks a lot for that :)
